# **Курс "Програмування на мові Python"**

## **Практичне зайняття №9**

### Тема: "Робота з функціями. Локальні та глобальні змінні"

### **Завдання 1 (3 бали)**

**Підрахувати визначник матриці, використовуючи правило перестановок.**

Функція random_matrix() призначена для створення квадратної матриці випадкових чисел. Її змінювати непотрібно.

Приклад використання методу permutations() для створення списку перестановок також подається у комірці з кодом.

1) Створити 3 функції: функцію створення списку перестановок, функцію підрахунку добутків та функцію підрахунку загальної суми.

2) Кожна функція має супроводжуватись рядком документації, що буде коротко описувати її призначення.

3) Розмірність квадратної матриці має вводитись користувачем з клавіатури. Підрахунки виконувати лише в тому разі, якщо користувач введе ціле додатне число.

4) Загальний результат повинен підраховуватись за допомогою композиції функцій.

За бажанням можна перевірити правильність роботи програми за допомогою функції np.linalg.det(a).

In [57]:
import numpy as np
import itertools

def random_matrix(dim):
    """
    The function generates dim x dim array of integers
    between 0 and 10.
    """
    matrix = np.random.randint(10, size = (dim, dim))
    return matrix

#Example of using permutations() method
g = list(itertools.permutations('123', 3))
def perestanovki(array,i,j):
    '''Функція шукає перестановки за допомогою delete з модуля numpy'''
    #Зріз виду [:] для 'копіювання'
    c = array[:]
    #Delete виду (змінна, підмасив, ось з якої треба видалити підмасив)
    c = np.delete(c, (i), axis = 0)
    return [np.delete(row, (j), axis = 0) for row in (c)]

def dobytki_suma(array):
    '''Функція для пошуку добутків, а також обробка простої матриці 1x1, 2x2'''
    # n - довжина рядків, еквівалентно вводу розміру матриці, array окрема змінна для зручності
    n = len(array)
    if n == 1 :
        return array[0][0]
    if n == 2 :
        return array[0][0]*array[1][1] - array[0][1]*array[1][0]
    sum = 0
    for i in range(0,n):
        m = perestanovki(array,0,i)
        sum =sum + ((-1)**i)*array[0][i] * dobytki_suma(m)
    return sum


try:
 a = int(input())
 if a <= 0:
    print('Oops! Size cannot be negative')
 else:
  m = random_matrix(a)
  print(m)
  #if n == 1 :return array[0][0]
  #if n == 2 :return array[0][0]*array[1][1] - array[0][1]*array[1][0]
  print('Result:', dobytki_suma(m))
  print('Result1:', np.linalg.det(m))
except ValueError:
    raise ValueError ('Oops!')

[[1 3 0]
 [5 8 1]
 [4 7 2]]
Result: -9
Result1: -8.999999999999998
